"""add category parent

Revision ID: 356c0e821e52
Revises: c4e81a7d2f90
Create Date: 2026-09-27 11:40:17.370405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356c0e821e52'
down_revision: Union[str, Sequence[str], None] = 'c4e81a7d2f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    # Named, so the downgrade can drop it by name.
    op.create_foreign_key(
        'fk_categories_parent_id',
        'categories',
        'categories',
        ['parent_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_categories_parent_id', 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###
