"""add catalog and order listing indexes

Revision ID: 41a61aca0a32
Revises: d3f81c6b2a54
Create Date: 2026-08-13 22:50:43.017506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a61aca0a32'
down_revision: Union[str, Sequence[str], None] = 'd3f81c6b2a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_created_at', 'orders', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_orders_cycle_created', 'orders', ['cycle_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_products_live_brand', 'products', ['brand'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_products_live_name', 'products', ['name'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_live_name', table_name='products', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_products_live_brand', table_name='products', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_orders_cycle_created', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    # ### end Alembic commands ###
