"""add trigram index for catalog search

Revision ID: 8bb0928ca06c
Revises: 41a61aca0a32
Create Date: 2026-08-14 07:34:01.401756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb0928ca06c'
down_revision: Union[str, Sequence[str], None] = '41a61aca0a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Not autogenerated: Alembic compares tables and indexes, and knows nothing about the
    # extension the index's operator class comes from. pg_trgm is trusted (PostgreSQL 13+),
    # so a plain database owner may create it — no superuser needed on managed hosting.
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_products_live_name_trgm', 'products', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_live_name_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
    # The extension is deliberately left in place: it is database-wide, nothing here can
    # know whether something else has come to depend on it, and dropping it would take
    # any such index with it.
