"""telegram-only auth

Revision ID: 9e7fa9bbcec2
Revises: eb5b7cb4b498
Create Date: 2026-08-13 12:56:28.413335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e7fa9bbcec2'
down_revision: Union[str, Sequence[str], None] = 'eb5b7cb4b498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_auth_sessions',
    sa.Column('link_payload', sa.String(length=64), nullable=False),
    sa.Column('poll_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_secret_hash')
    )
    op.create_index(op.f('ix_telegram_auth_sessions_chat_id'), 'telegram_auth_sessions', ['chat_id'], unique=False)
    op.create_index(op.f('ix_telegram_auth_sessions_link_payload'), 'telegram_auth_sessions', ['link_payload'], unique=True)
    op.create_index(op.f('ix_telegram_auth_sessions_user_id'), 'telegram_auth_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_pending_telegram_contacts_phone'), table_name='pending_telegram_contacts')
    op.drop_table('pending_telegram_contacts')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'phone_verified')
    # ### end Alembic commands ###
    # Dropping the table leaves its enum type behind in Postgres, and a later revision
    # re-adding an "otp_purpose" type would then fail on a name that is already taken.
    op.execute('DROP TYPE IF EXISTS otp_purpose')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Server defaults only so the downgrade survives a non-empty users table: both
    # columns are NOT NULL and there is nothing to restore into them — the passwords are
    # gone for good, and every account would have to be verified again.
    op.add_column('users', sa.Column('phone_verified', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False, server_default=''))
    op.create_table('pending_telegram_contacts',
    sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pending_telegram_contacts_pkey')),
    sa.UniqueConstraint('chat_id', name=op.f('pending_telegram_contacts_chat_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pending_telegram_contacts_phone'), 'pending_telegram_contacts', ['phone'], unique=True)
    op.create_table('otp_codes',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('purpose', postgresql.ENUM('REGISTER', 'LOGIN', 'RESET_PASSWORD', name='otp_purpose'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('consumed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('otp_codes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_codes_pkey'))
    )
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.drop_index(op.f('ix_telegram_auth_sessions_user_id'), table_name='telegram_auth_sessions')
    op.drop_index(op.f('ix_telegram_auth_sessions_link_payload'), table_name='telegram_auth_sessions')
    op.drop_index(op.f('ix_telegram_auth_sessions_chat_id'), table_name='telegram_auth_sessions')
    op.drop_table('telegram_auth_sessions')
    # ### end Alembic commands ###
