"""add product volume_ml

Revision ID: c996138b6b93
Revises: f2b6c4d18a37
Create Date: 2026-08-17 09:10:31.740307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c996138b6b93'
down_revision: Union[str, Sequence[str], None] = 'f2b6c4d18a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('volume_ml', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'volume_ml')
    # ### end Alembic commands ###
