"""add pending telegram contacts

Revision ID: ef66b2e63d7a
Revises: 8f0faa352fa8
Create Date: 2026-08-03 15:45:20.556419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef66b2e63d7a'
down_revision: Union[str, Sequence[str], None] = '8f0faa352fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_telegram_contacts',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_index(op.f('ix_pending_telegram_contacts_phone'), 'pending_telegram_contacts', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_telegram_contacts_phone'), table_name='pending_telegram_contacts')
    op.drop_table('pending_telegram_contacts')
    # ### end Alembic commands ###
