"""add product description html

Revision ID: fbab111e52ec
Revises: a9d34f10c7b2
Create Date: 2026-09-25 09:42:46.631870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbab111e52ec'
down_revision: Union[str, Sequence[str], None] = 'a9d34f10c7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description_html')
    # ### end Alembic commands ###
