/**
 * @file Automatically generated by barrelsby.
 */

export * from './auth-template/index'
export * from './base-layout/index'
export * from './catalog-template/index'
export * from './product-template/index'
